<a href="https://colab.research.google.com/github/SaxenaVaishnavi/Machine-Learning-Practices/blob/main/Week_1/Practice_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import pandas as pd

I have the dataset file on my drive with the link `https://drive.google.com/file/d/1Vl8jbcnqeJfzViFUZHBR-l4knO9iuDZB/view?usp=drive_link`

But `pandas.read_csv` does not directly support Google Drive links in this format `(https://drive.google.com/file/d/.../view)`.

**Converting the link:**

1. Extracting the **file ID** from the link. The file ID is the part after `/file/d/` and before `/view`.

  File ID: `1Vl8jbcnqeJfzViFUZHBR-l4knO9iuDZB`

2. Template of a downloadble link
  ```bash
  https://drive.google.com/uc?id=<FILE_ID>

3. Replacing `<FILE_ID>` with the actual file ID:
  ```bash
  https://drive.google.com/uc?id=1Vl8jbcnqeJfzViFUZHBR-l4knO9iuDZB

In [113]:
dataset_url = 'https://drive.google.com/uc?id=1Vl8jbcnqeJfzViFUZHBR-l4knO9iuDZB'
df = pd.read_csv(dataset_url)
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day
0,Jet Airways,Delhi,Banglore,DEL → BOM → COK,20:00,04:25 10 Jun,26h 35m,1 stop,In-flight meal not included,14924,6,Thursday,6.0
1,Jet Airways,Delhi,Cochin,DEL → BOM → COK,16:00,19:00 10 Jun,27h,1 stop,In-flight meal not included,10577,6,Sunday,9.0
2,Jet Airways,Mumbai,Hyderabad,BOM → HYD,19:35,21:05,1h 30m,non-stop,No info,5678,3,Friday,15.0
3,Multiple carriers,Delhi,Banglore,DEL → BOM → COK,18:55,01:30 16 Jun,15h 10m,1 stop,In-flight meal not included,7408,5,Monday,6.0
4,Air India,Delhi,Cochin,DEL → COK,17:10,17:55,8h 20m,non-stop,No info,6724,6,Monday,24.0

In [114]:
df.shape

(9450, 13)

# Problem 1

What is the average of the flight ticket price? Write your answer correct to two decimal places.

In [115]:
df['Price'].mean()

9027.895555555555

# Problem 2
During which month did the highest number of flights occur?

**NOTE**: Months are represented by numerical codes, with January corresponding to 1, February to 2, and so forth.

In [116]:
# Checking what months' data we have
print(f"Unique values in 'Month' column: {df['Month'].unique()}")

Unique values in 'Month' column: [6 3 5 4]

In [139]:
df.groupby('Month').count().max(axis=1)         # axis = 1: along rows or horizontally

Month
3    2388
4     926
5    3092
6    3044
dtype: int64

# Problem 3
Is the average price of flight tickets higher on weekends (Saturday and Sunday) or on weekdays (Remaining 5 days)?

In [118]:
weekends = ['Saturday', 'Sunday']
df['IsWeekend'] = df['WeekDay'].isin(weekends)      # Creating a new col in df that saves a flag value whether it was a weekend flight or not
df[['WeekDay', 'IsWeekend']].head()

    WeekDay  IsWeekend
0  Thursday      False
1    Sunday       True
2    Friday      False
3    Monday      False
4    Monday      False

In [119]:
# Calculating the average price for weekends and weekdays
average_price_weekends = df[df['IsWeekend'] == True]['Price'].mean()
average_price_weekdays = df[df['IsWeekend'] == False]['Price'].mean()

print(f"Average Price on Weekends: {average_price_weekends}")
print(f"Average Price on Weekdays: {average_price_weekdays}")

Average Price on Weekends: 9058.016077170418
Average Price on Weekdays: 9015.219666215608

# Problem 4
Two of the entries in the 'Additional_Info' column are 'No info' and 'No Info'. Replace all occurrences of 'No Info' with 'No info'. How many flights fall under airline 'IndiGo' and have 'No info' as additional information?

In [120]:
# Changing all occurences of  'No Info' with 'No info'
df['Additional_Info'] = df['Additional_Info'].replace('No Info', 'No info')

# Filtering out rows based on particular conditions
indiGo_no_info = df[(df['Airline'] == 'IndiGo') & (df['Additional_Info'] == 'No info')]

# Counting the number of such flights
num_flights = indiGo_no_info.shape[0]
print(f'Number of IndiGo flights with \'No info\' attribute: {num_flights}')

Number of IndiGo flights with 'No info' attribute: 1650

# Problem 5
Convert the values of 'Duration' into seconds. Enter the average duration (in seconds) of a flight. Enter your answer correct to two decimal places.

In [121]:
# Converting duration into seconds
duration = df['Duration']                                   # Extracting the 'Duration' col from df
seconds = []

for time in duration:                                       # Every entry ('time') is like '__h __m'
  time_components = time.split()                            # Splitting time into a list of components as ['__h', '__m']
  hours, minutes = 0, 0

  component_1 = time_components[0]                          # We are losing the unit h and m and just retaining the int part
  hours = int(component_1[0: len(component_1) - 1])

  if len(time_components) > 1:                              # This if condition is to take care of the cases where there is no minutes component
    component_2 = time_components[1]
    minutes = int(component_2[0: len(component_2) - 1])

  seconds.append(hours*3600 + minutes*60)

df['Duration'] = seconds
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day,IsWeekend
0,Jet Airways,Delhi,Banglore,DEL → BOM → COK,20:00,04:25 10 Jun,95700,1 stop,In-flight meal not included,14924,6,Thursday,6.0,False
1,Jet Airways,Delhi,Cochin,DEL → BOM → COK,16:00,19:00 10 Jun,97200,1 stop,In-flight meal not included,10577,6,Sunday,9.0,True
2,Jet Airways,Mumbai,Hyderabad,BOM → HYD,19:35,21:05,5400,non-stop,No info,5678,3,Friday,15.0,False
3,Multiple carriers,Delhi,Banglore,DEL → BOM → COK,18:55,01:30 16 Jun,54600,1 stop,In-flight meal not included,7408,5,Monday,6.0,False
4,Air India,Delhi,Cochin,DEL → COK,17:10,17:55,30000,non-stop,No info,6724,6,Monday,24.0,False

In [122]:
# Finding average of flight duration in seconds
df['Duration'].mean()

38959.80952380953

#Transform
the values in the 'dep_time' and 'arrival_time' columns to represent the hour component. For instance, if an entry is 10:05 June 13 or 10:05, the corresponding value should be 10.

Then convert the time into four categories as follows:

- 5 <= hour < 12 = Morning
- 12 <= hour < 17 = Afternoon
- 17 <= hour < 20 = Evening
- 20 <= hour < 5 = Night

**Note**: Please ensure that you make the changes directly within the dataset and continue to use that modified dataset for subsequent questions.

In [123]:
# Transformation 1: replacing Dep_Time and Arrival_Time with hour components

def replaceWithHourComponent(col):
  ''' Input - col that is to be replaced by its hour component
      Output - a list that is to replace the col column of the df '''

  original_col_values = df[col]
  transformed_col_values = []
  for i in range(len(original_col_values)):
    hour_component = original_col_values[i].split()[0].split(':')[0]
    transformed_col_values.append(hour_component)

  return transformed_col_values

df['Dep_Time'] = replaceWithHourComponent('Dep_Time')
df['Arrival_Time'] = replaceWithHourComponent('Arrival_Time')

df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day,IsWeekend
0,Jet Airways,Delhi,Banglore,DEL → BOM → COK,20,04,95700,1 stop,In-flight meal not included,14924,6,Thursday,6.0,False
1,Jet Airways,Delhi,Cochin,DEL → BOM → COK,16,19,97200,1 stop,In-flight meal not included,10577,6,Sunday,9.0,True
2,Jet Airways,Mumbai,Hyderabad,BOM → HYD,19,21,5400,non-stop,No info,5678,3,Friday,15.0,False
3,Multiple carriers,Delhi,Banglore,DEL → BOM → COK,18,01,54600,1 stop,In-flight meal not included,7408,5,Monday,6.0,False
4,Air India,Delhi,Cochin,DEL → COK,17,17,30000,non-stop,No info,6724,6,Monday,24.0,False

In [124]:
# Transformation 2: substituting hours with categories of time

def categorizeTime(col):
  original_col_values = df[col]
  transformed_col_values = []

  for i in range(len(original_col_values)):
    hour = int(original_col_values[i])
    if hour>=5 and hour<12:
      transformed_col_values.append('Morning')
    elif hour>=12 and hour<17:
      transformed_col_values.append('Afternoon')
    elif hour>=17 and hour<20:
      transformed_col_values.append('Evening')
    else:
      transformed_col_values.append('Night')

  return transformed_col_values

df['Dep_Time'] = categorizeTime('Dep_Time')
df['Arrival_Time'] = categorizeTime('Arrival_Time')

df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month,WeekDay,Day,IsWeekend
0,Jet Airways,Delhi,Banglore,DEL → BOM → COK,Night,Night,95700,1 stop,In-flight meal not included,14924,6,Thursday,6.0,False
1,Jet Airways,Delhi,Cochin,DEL → BOM → COK,Afternoon,Evening,97200,1 stop,In-flight meal not included,10577,6,Sunday,9.0,True
2,Jet Airways,Mumbai,Hyderabad,BOM → HYD,Evening,Night,5400,non-stop,No info,5678,3,Friday,15.0,False
3,Multiple carriers,Delhi,Banglore,DEL → BOM → COK,Evening,Night,54600,1 stop,In-flight meal not included,7408,5,Monday,6.0,False
4,Air India,Delhi,Cochin,DEL → COK,Evening,Evening,30000,non-stop,No info,6724,6,Monday,24.0,False

# Problem 6

How many flights started in the Morning and arrived the destination at Evening?

In [125]:
## Solution ##
selected_df = df[(df['Dep_Time'] == 'Morning') & (df['Arrival_Time'] == 'Evening')]
selected_df.shape

(922, 14)

# Problem 7
Encode the values of column 'WeekDay' as follows:
- Weekends (Sunday, Saturday) = 1
- all remaining five days = 0

What is the most frequent (mode) WeekDay?

In [136]:
## Solution ##
df['WeekDay_Encoded'] = df['WeekDay'].apply(lambda x: 1 if x in ['Saturday', 'Sunday'] else 0)

df.groupby('WeekDay_Encoded').count().max(axis=1)

WeekDay_Encoded
0    6651
1    2799
dtype: int64

In [138]:
df.groupby('WeekDay').count().max(axis=1)

WeekDay
Friday        834
Monday       1597
Saturday     1546
Sunday       1253
Thursday     1590
Tuesday       737
Wednesday    1893
dtype: int64